### ISSUE TITLE
As a user, I want to be able to edit my profile. - JS

### ISSUE THREAD

**Issue by MiltiadisTavelis** [CS-UCY-EPL343/epl449.spring21.team15.ReserveOnTime#27]

**Comment by MIltiadisTavelis** [comment]
var name = document.getElementById('firstname-input');
    var surname = document.getElementById('lastname-input');
    var gender = document.getElementById('gender-input');
    var birthday = document.getElementById('date-input');
    var code = document.getElementById('telcode-input');
    var number = document.getElementById('tel-input');
    var email = document.getElementById('email-input');
    var xhr = new XMLHttpRequest();
    var data = {
        "type": "users/update",
        "fname": name.value,
        "lname": surname.value,
        "email": email.value,
        "pnum": number.value,
        "phone_code": code.value,
        "birth": birthday.value,
        "gender": gender.value,
    };

    xhr.onload = function() {
        if (xhr.status === 200) {
            var response = JSON.parse(xhr.responseText);

            if (response.hasOwnProperty('status')) {
                popUpMessage(response["status"], "success");
            }else{
	            popUpMessage("There was an unexpected error", "danger");
        	}
        } else {
            popUpMessage("There was an unexpected error", "danger");
        }
    }
    xhr.withCredentials = true;
    xhr.open('PUT', api);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify(data));
