### ISSUE TITLE
As a user, I want to be able to view the availability of the shop - BACK END

### ISSUE THREAD

**Issue by MiltiadisTavelis** [CS-UCY-EPL343/epl449.spring21.team15.ReserveOnTime#30]

**Comment by MIltiadisTavelis** [comment]
<?php
	if(count(get_included_files()) == 1){
		echo json_encode(array('status' => 'Bad Request'));
		return;
	};

	$database = new Connection();
	$db = $database->connect();

	$shops = new Shops($db);

	$shops->id = $data['shop_id'];
	$results = $shops->isFull();

	if($results == true ){
		echo json_encode(array('status' => 'Full'));
	}else{
		echo json_encode(array('status' => 'Available'));
	}
?>

**Comment by MIltiadisTavelis** [comment]
<?php
	if(count(get_included_files()) == 1){
		echo json_encode(array('status' => 'Bad Request'));
		return;
	};

	//include_once '../../config/config.php';
	//include_once '../../models/shops.php';

	$database = new Connection();
	$db = $database->connect();

	$shops = new Shops($db);

	$shops->id = $data['shop_id'];
	$results = $shops->isFull();

	if($results == true ){
		echo json_encode(array('status' => 'Full'));
	}else{
		echo json_encode(array('status' => 'Available'));
	}
?>

**Comment by MIltiadisTavelis** [comment]
<?php
	if(count(get_included_files()) == 1){
		echo json_encode(array('status' => 'Bad Request'));
		return;
	};

	//include_once '../../config/config.php';
	//include_once '../../models/shops.php';

	$database = new Connection();
	$db = $database->connect();

	$shops = new Shops($db);

	$shops->id = $data['shop_id'];
	$results = $shops->isFull();

	if($results == true ){
		echo json_encode(array('status' => 'Full'));
	}else{
		echo json_encode(array('status' => 'Available'));
	}
?>
